# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 16:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=500)),
                ('recurring', models.BooleanField()),
                ('date_type', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=500)),
                ('created', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('last_send', models.DateTimeField()),
                ('next_send', models.DateTimeField()),
                ('interval', models.IntegerField()),
                ('interval_type', models.CharField(max_length=50)),
                ('snooze', models.BooleanField()),
                ('snooze_interval', models.IntegerField()),
                ('snooze_interval_type', models.CharField(max_length=50)),
                ('snooze_last_send', models.DateTimeField()),
                ('snooze_next_send', models.DateTimeField()),
                ('warning', models.BooleanField()),
                ('warning_interval', models.IntegerField()),
                ('warning_interval_type', models.CharField(max_length=50)),
                ('warning_next_send', models.DateTimeField()),
                ('in_deleted', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
