# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='interval',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='interval_type',
            field=models.CharField(choices=[('day', 'day(s)'), ('week', 'week(s)'), ('month', 'month(s)'), ('year', 'year(s)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_send',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='snooze',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='snooze_interval',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='snooze_interval_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='snooze_last_send',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='snooze_next_send',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='warning_interval',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='warning_interval_type',
            field=models.CharField(choices=[('day', 'day(s)'), ('week', 'week(s)'), ('month', 'month(s)'), ('year', 'year(s)')], max_length=50),
        ),
    ]
