# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_auto_20171122_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagelog',
            name='event',
        ),
        migrations.RemoveField(
            model_name='messagelog',
            name='user',
        ),
        migrations.AddField(
            model_name='messagelog',
            name='event_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='sent',
            field=models.DateTimeField(null=True),
        ),
    ]
