# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0004_auto_20171122_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagelog',
            old_name='user_id',
            new_name='users_id',
        ),
    ]
